import 'package:get/get_navigation/src/root/internacionalization.dart';

import '../base/globalization.dart';

class LanguageValue extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          Globalization.login: "login",
          Globalization.setting: "setting",
          Globalization.language:"Language",
          Globalization.bluetooth:"Bluetooth",
          Globalization.open:"Open",
          Globalization.close:"Close",
          Globalization.brightness:"Brightness",
          Globalization.userManagement:"UserManagement",
          Globalization.mode:"Mode",
          Globalization.time:"Time",
          Globalization.power:"Power",
          Globalization.soundIntensity:"SoundIntensity",
          Globalization.pPower:"Power",
          Globalization.pSoundIntensity:"SoundIntensity",
          Globalization.frequency:"Frequency",
          Globalization.start:"Start",
          Globalization.stop:"Stop",
          Globalization.details:"Details",
          Globalization.intensity:"Intensity",
          Globalization.vibration:"Vibration",
          Globalization.currEmStSt:"Current Emergency Stop State",
          Globalization.currNorSt:"Current Normal State",
          Globalization.pulseWidthA:"Pulse Width(A)",
          Globalization.pulseWidthB:"Pulse Width(B)",
          Globalization.delayTime:"Delay Time",
          Globalization.pulsePeriod:"Pulse Period",
          Globalization.intensityA:"Intensity(A)",
          Globalization.intensityB:"Intensity(B)",
          Globalization.pulseWidth:"Pulse Width",
          Globalization.recipe:"Recipe",
          Globalization.ultrasound:"Ultrasound Therapy",
          Globalization.pulse:"Pulse Magnetic Therapy",
          Globalization.infrared:"Infrared Polarized Light Therapy",
          Globalization.electricity:"Electrotherapy",
          Globalization.spasm:"SpasmMuscle",
          Globalization.tens:"TENS",
          Globalization.muscle:"MuscleStimulator",
          Globalization.medium:"MediumFrequency/InterferentialCurrent",
          Globalization.name:"Name",
          Globalization.tel:"Tel",
          Globalization.no:"No.",
          Globalization.age:"Age",
          Globalization.gender:"Gender",
          Globalization.certificate:"Certificate",
          Globalization.hospitalNo:"Hospital No.",
          Globalization.bedNo:"Bed No.",
          Globalization.editInfo:"EditInformation",
          Globalization.treatmentRecords:"Treatment Records",
          Globalization.startTreatment:"Start treatment",
          Globalization.newUsers:"New Users",
          Globalization.save:"Save",
          Globalization.cancel:"Cancel",
          Globalization.addUser:"Add user",
          Globalization.theme:"Integrated Physiotherapy System",
          Globalization.rememberPassword:"Remember password",
          Globalization.version:"Current Version Number",
          Globalization.confirm:"Confirm",
          Globalization.userName:"Please input username",
          Globalization.password:"Please input password",
          Globalization.continuous:"Continuous",
          Globalization.intermittentOne:"intermittent1",
          Globalization.intermittentTwo:"intermittent2",
          Globalization.intermittentThree:"intermittent3",
          Globalization.fast:"Fast Intermittent",
          Globalization.slow:"Slow Intermittent",
          Globalization.complete:"Complete denervation",
          Globalization.partial:"Partial denervation",
          Globalization.factory:"FactorySettings",
          Globalization.sweep:"SweepFrequency",
          Globalization.output:"OutputPower",
          Globalization.operate:"OperatingInstruction",
          Globalization.attention:"Precautions",
          Globalization.back:"Back",
          Globalization.link:"AbnormalLink",
          Globalization.temper:"NormalTemperature",
        },
        "zh_CN": {
          Globalization.login: "登录",
          Globalization.setting: "设置",
          Globalization.language:"语言",
          Globalization.bluetooth:"蓝牙",
          Globalization.open:"打开",
          Globalization.close:"关闭",
          Globalization.brightness:"亮度调节",
          Globalization.userManagement:"用户管理",
          Globalization.mode:"模式",
          Globalization.time:"时间",
          Globalization.power:"功率",
          Globalization.soundIntensity:"声强",
          Globalization.pPower:"输出功率",
          Globalization.pSoundIntensity:"有效声强",
          Globalization.frequency:"频率",
          Globalization.start:"开始",
          Globalization.stop:"停止",
          Globalization.details:"详情",
          Globalization.intensity:"强度",
          Globalization.vibration:"振动",
          Globalization.currEmStSt:"当前急停状态",
          Globalization.currNorSt:"当前正常状态",
          Globalization.pulseWidthA:"脉宽(A)",
          Globalization.pulseWidthB:"脉宽(B)",
          Globalization.delayTime:"延时时间",
          Globalization.pulsePeriod:"脉冲周期",
          Globalization.intensityA:"强度(A)",
          Globalization.intensityB:"强度(B)",
          Globalization.pulseWidth:"脉宽",
          Globalization.recipe:"处方",
          Globalization.ultrasound:"超声疗法",
          Globalization.pulse:"脉冲磁疗法",
          Globalization.infrared:"红外偏振光治疗",
          Globalization.electricity:"电疗",
          Globalization.spasm:"痉挛肌治疗",
          Globalization.tens:"经皮神经电刺激",
          Globalization.muscle:"神经肌肉电刺激",
          Globalization.medium:"中频/干扰电治疗",
          Globalization.name:"姓名",
          Globalization.tel:"电话",
          Globalization.no:"编号",
          Globalization.age:"年龄",
          Globalization.gender:"性别",
          Globalization.certificate:"证件",
          Globalization.hospitalNo:"住院号",
          Globalization.bedNo:"床号",
          Globalization.editInfo:"编辑信息",
          Globalization.treatmentRecords:"治疗记录",
          Globalization.startTreatment:"开始治疗",
          Globalization.newUsers:"新增用户",
          Globalization.save:"保存",
          Globalization.cancel:"取消",
          Globalization.addUser:"添加用户",
          Globalization.theme:"综合物理治疗系统",
          Globalization.rememberPassword:"记住密码",
          Globalization.version:"当前版本号",
          Globalization.confirm:"确定",
          Globalization.userName:"请输入用户名",
          Globalization.password:"请输入密码",
          Globalization.continuous:"连续",
          Globalization.intermittentOne:"断续1",
          Globalization.intermittentTwo:"断续2",
          Globalization.intermittentThree:"断续3",
          Globalization.fast:"快速断续输出",
          Globalization.slow:"慢速断续输出",
          Globalization.complete:"完全失神经",
          Globalization.partial:"部分失神经",
          Globalization.factory:"出厂设置",
          Globalization.sweep:"扫频",
          Globalization.output:"输出功率",
          Globalization.operate:"操作说明",
          Globalization.attention:"注意事项",
          Globalization.back:"返回",
          Globalization.link:"链接异常",
          Globalization.temper:"温度正常",
        }
      };
}
